package pl.mateusz.drozdz.fishing_essentials.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLACES.
 */
public class Places {

    private Long id;
    private String name;
    private String description;
    private String latitude;
    private String longitude ;
    private java.util.Date date;

    public Places() {
    }

    public Places(Long id) {
        this.id = id;
    }

    public Places(Long id, String name, String description, String latitude, String longitude , java.util.Date date) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.latitude = latitude;
        this.longitude  = longitude ;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude () {
        return longitude ;
    }

    public void setLongitude (String longitude ) {
        this.longitude  = longitude ;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
